notARepository: "quit"

os:
  editPreset: nvim

gui:
  showBottomLine: false
  border: rounded
  nerdFontsVersion: "3"

git:
  fetchAll: false
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
